ZRTSS-81 remove redundant reference to errno to fix build error with armclang
Source: Alif Semiconductor
JIRA ID: ZRTSS-81
Type: Defect Fix
Disposition: Local
Description:
The errno is defined as
extern _ARMABI_PURE volatile int * __aeabi_errno_addr()
instead of '* z_errno()' in armclang's errno.h that causes
the following error:
-- snip --
.../modules/hal/alif/se_services/
zephyr/src/se_service.c:24:12: error: conflicting types for '__aeabi_errno_addr'
extern int errno;
           ^
.../developmentstudio-2021.0/sw/ARMCompiler6.16/bin/../include/errno.h:47:26: not
e: expanded from macro 'errno'
                         ^
.../developmentstudio-2021.0/sw/ARMCompiler6.16/bin/../include/errno.h:32:35: note: previous declaration is here
extern _ARMABI_PURE volatile int *__aeabi_errno_addr(void);
                                  ^
1 error generated.
modules/alif/CMakeFiles/..__modules__hal__alif.dir/build.make:89: recipe for target 'modules/alif/CMakeFiles/..__modules__hal__alif.dir/se_services/zephyr/src/se_service.o' failed
-- snip --

Reviewed-by: Hemanth Kumar <hemanth@alifsemi.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jagadeesh@alifsemi.com>
Change-Id: I5969bc8d9fb11f53bbe8793457f88777ebab1681