common se_services: Fix build error with Zephyr v3.6
- Include cmsis_core.h instead of zephyr/arch/arm/aarch32/cortex_m/cmsis.h
to compile application with Zephyr v3.6.
- Update formal arguments of the init functions for Zephyr v3.6.

The above solve the following warning and error.
-- snip --
.../alif/common/src/mram_rw.c:12:10: fatal error:
'zephyr/arch/arm/aarch32/cortex_m/cmsis.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[87/116] Building C object .../se_services/zephyr/src/se_service.o
.../alif/se_services/zephyr/src/se_service.c:787:1: warning:
incompatible function pointer types initializing 'int (*)(void)' with
an expression of type 'int (const struct device *)'
[-Wincompatible-function-pointer-types]
SYS_INIT(se_service_mhuv2_nodes_init, POST_KERNEL,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../zephyr_3.6/include/zephyr/init.h:190:2: note: expanded from
macro 'SYS_INIT'
        SYS_INIT_NAMED(init_fn, init_fn, level, prio)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../zephyr_3.6/include/zephyr/init.h:208:32: note: expanded from
macro 'SYS_INIT_NAMED'
                Z_INIT_ENTRY_NAME(name) = {{ (init_fn_) }, { NULL } }
                                             ^~~~~~~~~~
1 warning generated.
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jagadeesh@alifsemi.com>